hp_intro: This is the entry
social_link:
  - name: Facebook
    url: facebook.com
  - name: Email
    url: 'mailto:lisa_ye@libero.it  '
hp_images:
  - image: /assets/screen-shot-2016-09-11-at-19.11.23.png
