hp_intro: >-
  Bacon ipsum dolor amet andouille kevin fatback ham hock sirloin. Tail strip
  steak beef tri-tip biltong filet mignon. Tri-tip pork spare ribs doner short
  ribs turducken. Drumstick salami brisket, pork belly rump pork chop
  frankfurter landjaeger pastrami burgdoggen beef bresaola. Kevin biltong cow
  venison shankle tail picanha. Venison cupim sirloin doner, jowl short ribs
  chuck t-bone sausage tenderloin. Tail pork leberkas biltong ball tip jerky
  porchetta turducken.


  > Bacon is the best!
social_link:
  - name: Facebook
    url: facebook.com
  - name: Email
    url: 'mailto:lisa_ye@libero.it  '
hp_images: []
